# Generated by Django 4.1.2 on 2022-10-05 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ovs_conf", "0004_port"),
    ]

    operations = [
        migrations.AlterField(
            model_name="port",
            name="ingress_policing_burst",
            field=models.IntegerField(blank=True, max_length=30000, null=True),
        ),
        migrations.AlterField(
            model_name="port",
            name="ingress_policy_rate",
            field=models.IntegerField(blank=True, max_length=30000, null=True),
        ),
        migrations.AlterField(
            model_name="port",
            name="interface",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="port",
            name="key",
            field=models.IntegerField(blank=True, max_length=30000),
        ),
        migrations.AlterField(
            model_name="port",
            name="remote_ip",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="port",
            name="tag",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(4095),
                ],
            ),
        ),
    ]
