# Generated by Django 4.1.2 on 2022-10-05 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ovs_conf", "0009_alter_port_ingress_policing_burst_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="port",
            name="bridge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ovs_conf.ovsbridge"
            ),
        ),
        migrations.CreateModel(
            name="TrunkPort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trunk", models.IntegerField()),
                (
                    "port",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ovs_conf.port"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OtherPortConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("other_config", models.CharField(max_length=50)),
                (
                    "port",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ovs_conf.port",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IpPort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.IntegerField()),
                (
                    "port",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ovs_conf.port"
                    ),
                ),
            ],
        ),
    ]
