# Generated by Django 4.1.2 on 2022-10-16 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ovs_conf", "0010_alter_port_bridge_trunkport_otherportconfig_ipport"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("mac", models.CharField(max_length=50)),
                ("pci", models.CharField(max_length=50)),
                (
                    "interface",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ovs_conf.port"
                    ),
                ),
            ],
        ),
    ]
