# Generated by Django 4.1.2 on 2022-10-22 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "ovs_conf",
            "0012_domainvm_alter_ovsbridge_options_alter_port_options_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Vm",
        ),
    ]
