# Generated by Django 4.1.2 on 2022-10-24 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ovs_conf", "0017_subelemodel_fkey_subelemodel_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subelemodel",
            name="fkey",
        ),
    ]
