# Generated by Django 4.1.2 on 2022-10-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OvsBridges",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("rstp_enable", models.BooleanField(default=False)),
                ("enable_ipv6", models.BooleanField(default=False)),
            ],
        ),
    ]
