# Generated by Django 4.1.2 on 2022-10-05 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ovs_conf", "0002_otherbridgeconfig"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OvsBridges",
            new_name="OvsBridge",
        ),
    ]
