# Generated by Django 4.1.2 on 2022-10-05 07:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ovs_conf", "0003_rename_ovsbridges_ovsbridge"),
    ]

    operations = [
        migrations.CreateModel(
            name="Port",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("internal", "Internal"),
                            ("system", "System"),
                            ("dpdk", "Dpdk"),
                            ("dpdkvhostuserclient", "Dpdkvhostuserclient"),
                            ("tap", "Tap"),
                            ("vxl", "Vxlan"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tag",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4095),
                        ]
                    ),
                ),
                (
                    "vlan_mode",
                    models.CharField(
                        choices=[
                            ("access", "Access"),
                            ("native-tagged", "Native Tagged"),
                            ("native-untagged", "Native Untagged"),
                            ("trunk", "Trunk"),
                        ],
                        max_length=15,
                    ),
                ),
                ("interface", models.CharField(max_length=100)),
                ("mac", models.CharField(max_length=100)),
                ("remote_ip", models.CharField(max_length=100)),
                ("remote_port", models.IntegerField(default=4789)),
                ("key", models.IntegerField(max_length=30000)),
                ("ingress_policy_rate", models.IntegerField(max_length=30000)),
                ("active", models.BooleanField(default=True)),
                ("ingress_policing_burst", models.IntegerField(max_length=30000)),
                (
                    "bridge",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ovs_conf.ovsbridge",
                    ),
                ),
            ],
        ),
    ]
