# Generated by Django 4.1.2 on 2022-10-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ovs_conf", "0006_alter_port_mac"),
    ]

    operations = [
        migrations.AlterField(
            model_name="port",
            name="key",
            field=models.IntegerField(blank=True, max_length=30000, null=True),
        ),
    ]
