# Generated by Django 4.1.2 on 2022-10-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ovs_conf", "0008_alter_port_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="port",
            name="ingress_policing_burst",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="port",
            name="ingress_policy_rate",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="port",
            name="key",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
