# Generated by Django 4.1.2 on 2022-10-21 18:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ovs_conf", "0011_vm"),
    ]

    operations = [
        migrations.CreateModel(
            name="DomainVm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attr_type", models.CharField(max_length=5)),
                ("text_name", models.CharField(max_length=20)),
            ],
            options={
                "ordering": ["text_name"],
            },
        ),
        migrations.AlterModelOptions(
            name="ovsbridge",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="port",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="vm",
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="MetaVm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ovs_conf.domainvm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemoryVm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_memory",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1000),
                            django.core.validators.MaxValueValidator(10000),
                        ]
                    ),
                ),
                (
                    "vm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ovs_conf.domainvm",
                    ),
                ),
            ],
        ),
    ]
