# Generated by Django 4.1.2 on 2022-10-24 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ovs_conf", "0014_subelement"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SubElement",
            new_name="SubEleModel",
        ),
    ]
