# Generated by Django 4.1.2 on 2022-10-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ovs_conf", "0015_rename_subelement_subelemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="subelemodel",
            name="name",
            field=models.CharField(default="foo", max_length=100),
            preserve_default=False,
        ),
    ]
