# Generated by Django 4.1.2 on 2022-10-24 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ovs_conf", "0016_subelemodel_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="subelemodel",
            name="fkey",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="ovs_conf.domainvm",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subelemodel",
            name="text",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
