# Generated by Django 4.1.2 on 2022-10-24 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ovs_conf", "0018_remove_subelemodel_fkey"),
    ]

    operations = [
        migrations.AddField(
            model_name="subelemodel",
            name="fkey",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ovs_conf.subelemodel",
            ),
        ),
    ]
