# Generated by Django 4.1.2 on 2022-10-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ovs_conf", "0021_alter_subelemodel_fkey"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subelemodel",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="subelemodel",
            name="attributes",
            field=models.TextField(blank=True, default="{}", null=True),
        ),
    ]
